# Generated by Django 3.2.6 on 2021-09-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('rollnumber', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sub1', models.IntegerField(max_length=200)),
                ('sub2', models.IntegerField(max_length=200)),
                ('sub3', models.IntegerField(max_length=200)),
                ('sub4', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mark', to='students.college'),
        ),
    ]
